version: '2'

services:
  laboratory_unix:
    container_name: laboratory-unix
    image: ubuntu:latest
    command: sleep 86400
    ports:
    - 80:80
    volumes:
    - .:/app

  test_application:
    container_name: test_application
    ports:
    - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    build: test_application
